name: Github Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'

  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job was triggerred by event: ${{ github.event_name }}"
          echo "Name of the branch is ${{ github.ref }}"
      - uses: actions/checkout@v3.0.2
      - name: List files in the repo
        run: |
          echo "The repo ${{ github.repository }} contains the following files: "
          tree
